[package]
name = "botrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stores = {path="../../components/stores"}
guild-logger = {path="../../components/guild-logger"}

async-trait = "0.1"
tracing = "0.1"
tonic = "0.6"
prost = "0.9"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

twilight-model = "0.10.1"


[build-dependencies]
tonic-build = "0.5"