[package]
name = "dbrokerapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
futures = "0.3"
tokio = { version = "1.0", features = ["macros"] }
serde = "1.0"
reqwest = { version = "0.11", features = ["json"]}
thiserror = "1.0"
async-sse = "5.1"
serde_json = "1.0"
tarpc = { version = "0.27", features = ["tokio1"] }

twilight-model = "0.8"
twilight-cache-inmemory = "0.8"
