[package]
name = "axum-metrics-layer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {workspace = true}
metrics = "0.18"
tower = "0.4"