[package]
name = "isolatecell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.110"
v8 = "0.36"
cpu-time = "1.0"
tracing = "0.1"
