[package]
name = "isolatecell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = {workspace = true}
v8 = {workspace = true}
cpu-time = "1.0"
tracing = {workspace = true}
