use std::collections::HashMap;

use chrono::{DateTime, Utc};
use common::dispatch_event::{EventSource, VmDispatchEvent};
use guild_logger::{entry::CreateLogEntry, GuildLogSender};
use runtime_models::internal::script::ScriptMeta;
use scheduler_worker_rpc::{
    CreateScriptsVmReq, MetricEvent, SchedulerMessage, VmSessionShutdownEvent, WorkerMessage,
};
use stores::config::{PremiumSlotTier, Script};
use tokio::sync::oneshot;
use tracing::{error, info, warn};
use twilight_model::id::{marker::GuildMarker, Id};
use vm::vm::ShutdownReason;

use crate::{
    interval_timer_manager::TimerId,
    vmworkerpool::{VmWorkerPool, WorkerHandle},
};

/// Scheduler-side shadow of a live vm inside a worker process.
///
/// Travels with the [WorkerHandle] through the pool so that when the same
/// guild claims the worker again the still-running vm can be resumed instead
/// of recreated. Replaced when a vm for another guild is created on the
/// worker, cleared when the vm shuts down.
#[derive(Debug)]
pub struct SessionState {
    pub guild_id: Id<GuildMarker>,
    pub vm_session_id: u64,
}

/// A claimed worker and the scheduler side of the vm session running on it.
///
/// This is claim-scoped: it always holds a worker and is consumed when the
/// worker goes back to the pool. Guild-lifetime state (scripts, timers,
/// derived state) lives in the guild handler, which owns this and reacts to
/// the [SessionEvent]s produced by [Self::handle_worker_msg].
pub struct VmSession {
    guild_id: Id<GuildMarker>,
    logger: GuildLogSender,
    worker: WorkerHandle,

    /// Session id of the vm currently live (or being created) on the worker.
    /// Monotonic per guild, generated by the guild handler.
    vm_session_id: u64,
    dispatch_id_gen: u64,
    pending_acks: HashMap<u64, PendingAck>,

    /// True from vm creation until the vm's event loop first drains
    /// completely: dispatches sent while this is set queue behind the
    /// compilation and top level execution of every script, which is the
    /// expensive cold path. Used to label latency metrics.
    vm_cold: bool,
}

impl VmSession {
    /// Resumes the still-running vm on a re-claimed worker, the worker has to
    /// carry session state for this guild.
    pub fn resume(worker: WorkerHandle, guild_id: Id<GuildMarker>, logger: GuildLogSender) -> Self {
        let state = worker
            .session_state
            .as_ref()
            .expect("resume requires session state on the worker");
        assert_eq!(state.guild_id, guild_id, "resumed vm belongs to another guild");

        info!(worker_id = worker.worker_id, "resuming vm on re-claimed worker");

        Self {
            guild_id,
            logger,
            vm_session_id: state.vm_session_id,
            dispatch_id_gen: 0,
            pending_acks: HashMap::new(),
            worker,
            vm_cold: false,
        }
    }

    /// Creates a fresh vm on the worker, replacing whatever vm it was hosting.
    ///
    /// The worker is handed back on send failure so the caller can dispose of
    /// it as broken.
    pub fn create(
        worker: WorkerHandle,
        guild_id: Id<GuildMarker>,
        logger: GuildLogSender,
        vm_session_id: u64,
        scripts: Vec<Script>,
        premium_tier: Option<PremiumSlotTier>,
    ) -> Result<Self, WorkerHandle> {
        let mut session = Self {
            guild_id,
            logger,
            vm_session_id,
            dispatch_id_gen: 0,
            pending_acks: HashMap::new(),
            worker,
            vm_cold: false,
        };

        match session.send_create_scripts_vm(vm_session_id, scripts, premium_tier) {
            Ok(()) => Ok(session),
            Err(()) => Err(session.worker),
        }
    }

    /// Replaces the vm on the already claimed worker, used when the guild's
    /// scripts changed while a session was active.
    pub fn restart_vm(
        &mut self,
        new_vm_session_id: u64,
        scripts: Vec<Script>,
        premium_tier: Option<PremiumSlotTier>,
    ) -> Result<(), ()> {
        self.send_create_scripts_vm(new_vm_session_id, scripts, premium_tier)
    }

    fn send_create_scripts_vm(
        &mut self,
        session_id: u64,
        scripts: Vec<Script>,
        premium_tier: Option<PremiumSlotTier>,
    ) -> Result<(), ()> {
        let evt_id = self.gen_dispatch_id();
        self.vm_session_id = session_id;
        self.vm_cold = true;

        self.worker
            .tx
            .send(SchedulerMessage::CreateScriptsVm(CreateScriptsVmReq {
                seq: evt_id,
                session_id,
                guild_id: self.guild_id,
                premium_tier,
                scripts,
            }))
            .map_err(|_| ())?;

        self.pending_acks.insert(
            evt_id,
            PendingAck {
                dispatched_session_id: session_id,
                kind: PendingAckType::Restart,
                dispatched: None,
            },
        );

        self.worker.session_state = Some(SessionState {
            guild_id: self.guild_id,
            vm_session_id: session_id,
        });

        Ok(())
    }

    /// Sends an event to the vm, recording a pending ack for it.
    ///
    /// On send failure the worker is broken and the ack payload is handed back
    /// so the caller can retry on a new session.
    pub fn dispatch(
        &mut self,
        name: String,
        data: serde_json::Value,
        ack: PendingAckType,
        source: EventSource,
        ts: DateTime<Utc>,
    ) -> Result<(), PendingAckType> {
        let evt_id = self.gen_dispatch_id();

        match self.worker.tx.send(SchedulerMessage::Dispatch(VmDispatchEvent {
            name,
            seq: evt_id,
            value: data,
            source,
            source_timestamp: ts,
        })) {
            Ok(()) => {
                self.pending_acks.insert(
                    evt_id,
                    PendingAck {
                        dispatched_session_id: self.vm_session_id,
                        kind: ack,
                        dispatched: Some(DispatchMeta {
                            source,
                            source_timestamp: ts,
                            vm_cold: self.vm_cold,
                        }),
                    },
                );
                Ok(())
            }
            Err(_) => Err(ack),
        }
    }

    /// Asks the vm to finish its pending work and shut down gracefully, the
    /// worker will send a [WorkerMessage::Shutdown] for the current session
    /// when done.
    pub fn send_complete(&mut self) -> Result<(), ()> {
        self.worker.tx.send(SchedulerMessage::Complete).map_err(|_| ())
    }

    pub async fn recv(&mut self) -> Option<WorkerMessage> {
        self.worker.rx.recv().await
    }

    /// Handles a message received from the worker (`None` meaning the channel
    /// died), returning the events the guild handler needs to act on.
    pub fn handle_worker_msg(&mut self, msg: Option<WorkerMessage>) -> Vec<SessionEvent> {
        let Some(msg) = msg else {
            return vec![SessionEvent::Broken];
        };

        match msg {
            WorkerMessage::Shutdown(shutdown) => self.handle_shutdown_msg(shutdown),
            WorkerMessage::Ack(id) => {
                let Some(item) = self.pending_acks.remove(&id) else {
                    return Vec::new();
                };

                if let Some(meta) = &item.dispatched {
                    metrics::histogram!(
                        "dispatch_event_acked_latency",
                        "event_source" => crate::dispatch_metrics::event_source_label(meta.source),
                        "vm_cold" => if meta.vm_cold { "true" } else { "false" },
                    )
                    .record(crate::dispatch_metrics::elapsed_millis(meta.source_timestamp));
                }

                match item.kind {
                    PendingAckType::Dispatch(Some(resp)) => {
                        let _ = resp.send(());
                        Vec::new()
                    }
                    PendingAckType::Dispatch(None) => Vec::new(),
                    PendingAckType::ScheduledTask(task_id) => {
                        vec![SessionEvent::TaskAcked(task_id)]
                    }
                    PendingAckType::IntervalTimer(timer) => vec![SessionEvent::TimerAcked(timer)],
                    PendingAckType::Restart => Vec::new(),
                }
            }
            WorkerMessage::ScriptStarted(meta) => vec![SessionEvent::ScriptStarted(meta)],
            WorkerMessage::ScriptsInit => todo!(),
            WorkerMessage::NonePending => {
                // the vm's event loop has drained, script init is done and
                // future dispatches run against a warm vm
                self.vm_cold = false;

                if self.pending_acks.is_empty() {
                    vec![SessionEvent::VmIdle]
                } else {
                    Vec::new()
                }
            }
            WorkerMessage::TaskScheduled => vec![SessionEvent::TaskScheduled],
            WorkerMessage::GuildLog(entry) => {
                self.logger.log_raw(entry);
                Vec::new()
            }
            WorkerMessage::Hello(_) => {
                // handled when the connection is established, not applicable here
                unreachable!();
            }
            WorkerMessage::Metric(name, m, labels) => {
                self.handle_metric(name, m, labels);
                Vec::new()
            }
        }
    }

    fn handle_shutdown_msg(&mut self, shutdown: VmSessionShutdownEvent) -> Vec<SessionEvent> {
        if shutdown.guild_id != self.guild_id {
            // shutdown of the previous tenant's vm being drained by the worker
            return Vec::new();
        }

        let mut events = self.cancel_old_vm_session_pending_acks(shutdown.vm_session_id);

        match shutdown.reason {
            Some(ShutdownReason::DiscordInvalidRequestsRatelimit) => {
                self.logger.log(CreateLogEntry::critical(
                    "VM was forcibly shut down for issuing too many invalid discord \
                     requests. Your guild has also been temporarily blacklisted for this \
                     reason."
                        .to_string(),
                ));
            }
            Some(ShutdownReason::Runaway) => {
                self.logger.log(CreateLogEntry::critical(
                    "VM was forcibly shut down for blocking the thread for too long, this \
                     means you might have an infinite loop somewhere."
                        .to_string(),
                ));
            }
            Some(ShutdownReason::OutOfMemory) => {
                self.logger.log(CreateLogEntry::critical(
                    "VM ran out of memory, this should not normally happen from normal \
                     use but if this was not intentional abuse please join the support \
                     server and let us know."
                        .to_owned(),
                ));
                warn!("VM ran out of memory");
            }
            Some(ShutdownReason::Request) => {
                self.logger.log(CreateLogEntry::info(
                    "Vm was shut down gracefully.".to_owned(),
                ));
            }
            None => {
                error!("Unknown vm shutdown reason");
                self.logger.log(CreateLogEntry::error(
                    "Vm was shut down due to a unknown reason?".to_owned(),
                ));
            }
        }

        events.push(SessionEvent::VmShutdown {
            current_vm: shutdown.vm_session_id == self.vm_session_id,
            reason: shutdown.reason,
        });

        events
    }

    fn cancel_old_vm_session_pending_acks(&mut self, session_id: u64) -> Vec<SessionEvent> {
        let to_cancel = self
            .pending_acks
            .iter()
            .filter_map(|(id, pending)| {
                (pending.dispatched_session_id <= session_id).then_some(*id)
            })
            .collect::<Vec<_>>();

        let mut events = Vec::new();
        for id in to_cancel {
            let Some(pending) = self.pending_acks.remove(&id) else {
                continue;
            };

            match pending.kind {
                PendingAckType::Dispatch(_) => {}
                PendingAckType::ScheduledTask(task_id) => {
                    events.push(SessionEvent::TaskDispatchCancelled(task_id));
                }
                PendingAckType::IntervalTimer(timer) => {
                    events.push(SessionEvent::TimerDispatchCancelled(timer));
                }
                PendingAckType::Restart => {}
            }
        }

        events
    }

    fn handle_metric(&mut self, name: String, m: MetricEvent, labels: HashMap<String, String>) {
        let mut labels = labels
            .into_iter()
            .map(|(k, v)| metrics::Label::new(k, v))
            .collect::<Vec<_>>();

        if name != "dispatch_event_latency" {
            labels.push(metrics::Label::new("guild_id", self.guild_id.to_string()));
        }

        match m {
            MetricEvent::Gauge(action) => {
                let handle = metrics::gauge!(name, labels);
                match action {
                    scheduler_worker_rpc::GaugeEvent::Set(v) => handle.set(v),
                    scheduler_worker_rpc::GaugeEvent::Incr(v) => handle.increment(v),
                }
            }
            MetricEvent::Counter(action) => {
                let handle = metrics::counter!(name, labels);

                match action {
                    scheduler_worker_rpc::CounterEvent::Incr(v) => handle.increment(v),
                    scheduler_worker_rpc::CounterEvent::Absolute(v) => handle.absolute(v),
                }
            }
            MetricEvent::Histogram(action) => {
                metrics::histogram!(name, labels).record(action);
            }
        }
    }

    /// Returns the worker to the pool with the vm still alive; the session
    /// state stays on the handle so the vm can be resumed on a later claim.
    pub fn return_idle(self, pool: &VmWorkerPool) {
        debug_assert!(
            matches!(&self.worker.session_state, Some(s) if s.guild_id == self.guild_id),
            "idle return without session state on the handle"
        );
        pool.return_worker(self.worker, false);
    }

    /// Returns the worker to the pool after its vm shut down, clearing the
    /// session state so a later claim doesn't try to resume a dead vm.
    pub fn return_after_shutdown(mut self, pool: &VmWorkerPool) {
        self.worker.session_state = None;
        pool.return_worker(self.worker, false);
    }

    /// Disposes of a worker whose channel died: drains what's left of its
    /// messages and returns it as broken (the pool spawns a replacement).
    ///
    /// The drained events are returned so the guild handler can apply their
    /// side effects (db writes for acks etc.) before clearing claim state.
    pub fn destroy_broken(mut self, pool: &VmWorkerPool) -> Vec<SessionEvent> {
        let mut events = Vec::new();
        while let Ok(msg) = self.worker.rx.try_recv() {
            events.extend(self.handle_worker_msg(Some(msg)));
        }

        self.worker.session_state = None;
        pool.return_worker(self.worker, true);

        events
    }

    pub fn worker_id(&self) -> u64 {
        self.worker.worker_id
    }

    pub fn num_pending_acks(&self) -> usize {
        self.pending_acks.len()
    }

    fn gen_dispatch_id(&mut self) -> u64 {
        self.dispatch_id_gen += 1;
        self.dispatch_id_gen
    }
}

/// Things the guild handler needs to act on in response to worker messages,
/// produced by [VmSession::handle_worker_msg].
pub enum SessionEvent {
    /// A script finished its top level execution and reported its
    /// contributions.
    ScriptStarted(ScriptMeta),
    /// The vm acked a scheduled task dispatch.
    TaskAcked(u64),
    /// The vm acked an interval timer dispatch.
    TimerAcked(TimerId),
    /// A pending scheduled task dispatch was cancelled because the vm it was
    /// dispatched to shut down.
    TaskDispatchCancelled(u64),
    /// Same as [Self::TaskDispatchCancelled] for interval timers.
    TimerDispatchCancelled(TimerId),
    /// A script scheduled a new task.
    TaskScheduled,
    /// The vm has no pending work and no acks are outstanding; the worker can
    /// be returned to the pool with the vm kept alive.
    VmIdle,
    /// A vm belonging to this guild shut down. `current_vm` is false when it
    /// was an older vm of ours (e.g. replaced by a restart on this claim).
    VmShutdown {
        current_vm: bool,
        reason: Option<ShutdownReason>,
    },
    /// The channel to the worker died.
    Broken,
}

/// Guild handler -> scheduler notifications, produced when a vm was forcibly
/// shut down.
pub enum VmSessionEvent {
    ShutdownTooManyInvalidRequests,
    ShutdownExcessCpu,
}

pub struct PendingAck {
    dispatched_session_id: u64,
    kind: PendingAckType,
    /// Set for event dispatches (not vm restarts), used to record the acked
    /// latency metric.
    dispatched: Option<DispatchMeta>,
}

struct DispatchMeta {
    source: EventSource,
    source_timestamp: DateTime<Utc>,
    /// Whether the vm was still cold (see [VmSession::vm_cold]) when this
    /// event was dispatched to it.
    vm_cold: bool,
}

pub enum PendingAckType {
    Dispatch(Option<oneshot::Sender<()>>),
    ScheduledTask(u64),
    IntervalTimer(TimerId),
    Restart,
}
