#!/usr/bin/env node
// Merges ts-rs' one-file-per-type output into a single file per directory.
//
// ts-rs always writes one file per type (export_to is per-type and cannot be
// shared), so we collapse them afterwards: every `<dir>/<Type>.ts` is folded
// into a flat `<dir>.ts` and the directory is removed. Same-dir imports become
// dead and are dropped; cross-dir imports are deduped, hoisted, and repointed
// at the sibling module.
//
// This replaces the old gen-index.bash, which built an index of re-exports.
//
// Usage: merge-types.mjs <root>

import { readdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const HEADER =
  "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

// ts-rs emits single-line, single-name `import type { X } from "path";` but we
// accept value-syntax and multi-name forms so a codegen change doesn't silently
// leave a stray import in the body.
const IMPORT_RE = /^import\s+(?:type\s+)?\{\s*([^}]+?)\s*\}\s+from\s+"([^"]+)";?\s*$/;

const root = process.argv[2];
if (!root) {
  console.error("usage: merge-types.mjs <root>");
  process.exit(1);
}

function mergeDir(dirName) {
  const dir = join(root, dirName);
  const entries = readdirSync(dir, { withFileTypes: true });

  // The whole directory gets removed once merged, so refuse to run rather than
  // silently delete output we didn't fold in.
  for (const e of entries) {
    if (e.isDirectory()) {
      console.error(`  error: nested directory ${dirName}/${e.name} is not supported`);
      process.exit(1);
    }
  }

  // Sorted so regeneration is byte-stable and diffs stay minimal. Default JS
  // string sort is code-unit order, which matches LC_ALL=C for these names.
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith(".ts") && e.name !== "index.ts")
    .map((e) => e.name)
    .sort();

  if (files.length === 0) {
    console.log(`  ${dirName}: nothing to merge`);
    return;
  }

  // target dir -> Set of imported names
  const crossImports = new Map();
  const bodies = [];
  let droppedImports = 0;

  for (const file of files) {
    const body = [];

    for (const line of readFileSync(join(dir, file), "utf8").split("\n")) {
      if (line === HEADER) continue;

      const m = IMPORT_RE.exec(line);
      if (!m) {
        body.push(line);
        continue;
      }

      const names = m[1].split(",").map((n) => n.trim()).filter(Boolean);
      const path = m[2];

      if (path.startsWith("./")) {
        // Same directory: the type is local after merging.
        droppedImports++;
      } else if (path.startsWith("../")) {
        const target = path.split("/")[1];
        if (!crossImports.has(target)) crossImports.set(target, new Set());
        for (const n of names) crossImports.get(target).add(n);
      } else {
        console.warn(`  warning: ${dirName}/${file}: unrecognized import "${path}", kept verbatim`);
        body.push(line);
      }
    }

    bodies.push(body.join("\n").trim());
  }

  // Merged modules are siblings at the root, so cross-dir paths flatten too.
  const importLines = [...crossImports.keys()].sort().map((target) => {
    const names = [...crossImports.get(target)].sort().join(", ");
    return `import type { ${names} } from "./${target}";`;
  });

  const out = [HEADER, "", ...(importLines.length ? [...importLines, ""] : []), bodies.join("\n\n"), ""];
  writeFileSync(join(root, `${dirName}.ts`), out.join("\n"));

  rmSync(dir, { recursive: true });

  console.log(
    `  ${dirName}/ (${files.length} files) -> ${dirName}.ts ` +
      `(${droppedImports} same-dir imports dropped, ${importLines.length} cross-dir imports hoisted)`,
  );
}

const dirs = readdirSync(root, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

console.log(`merging ts-rs output in ${root}`);
for (const d of dirs) mergeDir(d);

// The root index intentionally re-exports nothing; consumers import the merged
// modules directly (./internal, ./discord, ./image) so that the
// Internal/Discord namespace split is preserved.
writeFileSync(join(root, "index.ts"), "// generated index file using merge-types.mjs\n");
