[package]
name = "tscompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = { version = "0.33.12", features = ["sourcemap"] }
swc_ecma_parser = "0.141.37"
swc_ecma_ast = "0.110.17"
sourcemap = "6.2"
swc = "0.270.18"
