[package]
name = "tscompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# swc = "0.24"
swc_common = {version = "0.29.27", features=["sourcemap"]}
swc_ecma_parser = "0.124.2"
swc_ecma_ast = "0.96"
# swc_ecmascript = {version = "0.114.2", features=["codegen", "parser", "transforms", "typescript", "visit", "compat"]}
sourcemap = "6.2"
swc = "0.244.3"
# swc_core = "0.58.4"
