[package]
name = "tscompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = { version = "0.33.21", features = ["sourcemap"] }
sourcemap = "6.2"
swc = "0.273.23"
swc_ecmascript = { version = "0.239.21", features = ["parser"] }
