[package]
name = "tscompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = {version = "0.29.27", features=["sourcemap"]}
swc_ecma_parser = "0.124.2"
swc_ecma_ast = "0.96"
sourcemap = "6.2"
swc = "0.244.3"
